#!/bin/sh

## Environment
export EDITOR=vim
export PATH="$PATH:$HOME/.scripts"
export _JAVA_AWT_WM_NONREPARENTING=1

## Configuration
feh -z --bg-fill --no-fehbg $HOME/Wallpapers
xrdb -merge $HOME/.Xresources
xsetroot -cursor_name left_ptr
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.55
xinput set-prop "SynPS/2 Synaptics TouchPad" "Coordinate Transformation Matrix" 1, 0, 0, 0, 0.5, 0, 0, 0, 1

FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')

bspc config borderless_monocle true
#bspc config gapless_monocle true
#bspc config paddingless_monocle true
bspc config single_monocle false
bspc config border_width 3
bspc config window_gap 5
bspc config top_padding 34
bspc config split_ration 0.52
bspc config focused_border_color "$WHITE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

#bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

## Rules
bspc rule -r *:*
bspc rule -a Conky sticky=on manage=off lower=on

## Programs
multihead.sh

run_bg.sh sxhkd
run_bg.sh udiskie

polybar.sh
picom.sh
